package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Acessorio generated by hbm2java
 */
@Entity
@Table(name = "acessorio", catalog = "locadora")
public class Acessorio implements java.io.Serializable {

	private Long codigo;
	private String descricao;
//	private Set<CarroAcessorio> carroAcessorios = new HashSet<CarroAcessorio>(0);
//	private Set<CarroAcessorio> carroAcessorios_1 = new HashSet<CarroAcessorio>(0);

	public Acessorio() {
	}

//	public Acessorio(String descricao, Set<CarroAcessorio> carroAcessorios, Set<CarroAcessorio> carroAcessorios_1) {
	public Acessorio(String descricao) {
		this.descricao = descricao;
//		this.carroAcessorios = carroAcessorios;
//		this.carroAcessorios_1 = carroAcessorios_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codigo", unique = true, nullable = false)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acessorio")
//	public Set<CarroAcessorio> getCarroAcessorios() {
//		return this.carroAcessorios;
//	}
//
//	public void setCarroAcessorios(Set<CarroAcessorio> carroAcessorios) {
//		this.carroAcessorios = carroAcessorios;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acessorio")
//	public Set<CarroAcessorio> getCarroAcessorios_1() {
//		return this.carroAcessorios_1;
//	}
//
//	public void setCarroAcessorios_1(Set<CarroAcessorio> carroAcessorios_1) {
//		this.carroAcessorios_1 = carroAcessorios_1;
//	}

}
