package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aluguel generated by hbm2java
 */
@Entity
@Table(name = "aluguel", catalog = "locadora")
public class Aluguel implements java.io.Serializable {

	private Long codigo;
	private Carro carro;
	private ApoliceSeguro apoliceSeguro;
	private Motorista motorista;
	private Date dataDevolucao;
	private Date dataEntrega;
	private Date dataPedido;
	private BigDecimal valorTotal;

	public Aluguel() {
	}

	public Aluguel(Carro carro, ApoliceSeguro apoliceSeguro, Motorista motorista, Date dataDevolucao, Date dataEntrega,
			Date dataPedido, BigDecimal valorTotal) {
		this.carro = carro;
		this.apoliceSeguro = apoliceSeguro;
		this.motorista = motorista;
		this.dataDevolucao = dataDevolucao;
		this.dataEntrega = dataEntrega;
		this.dataPedido = dataPedido;
		this.valorTotal = valorTotal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codigo", unique = true, nullable = false)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_carro")
	public Carro getCarro() {
		return this.carro;
	}

	public void setCarro(Carro carro) {
		this.carro = carro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_apolice_seguro")
	public ApoliceSeguro getApoliceSeguro() {
		return this.apoliceSeguro;
	}

	public void setApoliceSeguro(ApoliceSeguro apoliceSeguro) {
		this.apoliceSeguro = apoliceSeguro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_motorista")
	public Motorista getMotorista() {
		return this.motorista;
	}

	public void setMotorista(Motorista motorista) {
		this.motorista = motorista;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_devolucao", length = 26)
	public Date getDataDevolucao() {
		return this.dataDevolucao;
	}

	public void setDataDevolucao(Date dataDevolucao) {
		this.dataDevolucao = dataDevolucao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_entrega", length = 26)
	public Date getDataEntrega() {
		return this.dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_pedido", length = 10)
	public Date getDataPedido() {
		return this.dataPedido;
	}

	public void setDataPedido(Date dataPedido) {
		this.dataPedido = dataPedido;
	}

	@Column(name = "valor_total")
	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

}
