package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApoliceSeguro generated by hbm2java
 */
@Entity
@Table(name = "apolice_seguro", catalog = "locadora")
public class ApoliceSeguro implements java.io.Serializable {

	private Long codigo;
	private Boolean protecaoCausasNaturais;
	private Boolean protecaoRoubo;
	private Boolean protecaoTerceiro;
	private BigDecimal valorFranquia;
	private Set<Aluguel> aluguels = new HashSet<Aluguel>(0);
	private Set<Aluguel> aluguels_1 = new HashSet<Aluguel>(0);

	public ApoliceSeguro() {
	}

	public ApoliceSeguro(Boolean protecaoCausasNaturais, Boolean protecaoRoubo, Boolean protecaoTerceiro,
			BigDecimal valorFranquia, Set<Aluguel> aluguels, Set<Aluguel> aluguels_1) {
		this.protecaoCausasNaturais = protecaoCausasNaturais;
		this.protecaoRoubo = protecaoRoubo;
		this.protecaoTerceiro = protecaoTerceiro;
		this.valorFranquia = valorFranquia;
		this.aluguels = aluguels;
		this.aluguels_1 = aluguels_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codigo", unique = true, nullable = false)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "protecao_causas_naturais")
	public Boolean getProtecaoCausasNaturais() {
		return this.protecaoCausasNaturais;
	}

	public void setProtecaoCausasNaturais(Boolean protecaoCausasNaturais) {
		this.protecaoCausasNaturais = protecaoCausasNaturais;
	}

	@Column(name = "protecao_roubo")
	public Boolean getProtecaoRoubo() {
		return this.protecaoRoubo;
	}

	public void setProtecaoRoubo(Boolean protecaoRoubo) {
		this.protecaoRoubo = protecaoRoubo;
	}

	@Column(name = "protecao_terceiro")
	public Boolean getProtecaoTerceiro() {
		return this.protecaoTerceiro;
	}

	public void setProtecaoTerceiro(Boolean protecaoTerceiro) {
		this.protecaoTerceiro = protecaoTerceiro;
	}

	@Column(name = "valor_franquia")
	public BigDecimal getValorFranquia() {
		return this.valorFranquia;
	}

	public void setValorFranquia(BigDecimal valorFranquia) {
		this.valorFranquia = valorFranquia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apoliceSeguro")
	public Set<Aluguel> getAluguels() {
		return this.aluguels;
	}

	public void setAluguels(Set<Aluguel> aluguels) {
		this.aluguels = aluguels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apoliceSeguro")
	public Set<Aluguel> getAluguels_1() {
		return this.aluguels_1;
	}

	public void setAluguels_1(Set<Aluguel> aluguels_1) {
		this.aluguels_1 = aluguels_1;
	}

}
