package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carro generated by hbm2java
 */
@Entity
@Table(name = "carro", catalog = "locadora")
public class Carro implements java.io.Serializable {

	private Long codigo;
	private Modelocarro modelocarro;
	private String chassi;
	private String cor;
	private String placa;
	private BigDecimal valorDiaria;
	private Date dataCriacao;
	private Date dataModificacao;
	private byte[] foto;
	private Set<CarroAcessorio> carroAcessorios = new HashSet<CarroAcessorio>(0);
	private Set<CarroAcessorio> carroAcessorios_1 = new HashSet<CarroAcessorio>(0);
	private Set<Aluguel> aluguels = new HashSet<Aluguel>(0);
	private Set<Aluguel> aluguels_1 = new HashSet<Aluguel>(0);

	public Carro() {
	}

	public Carro(Modelocarro modelocarro, String chassi, String cor, String placa, BigDecimal valorDiaria,
			Date dataCriacao, Date dataModificacao, byte[] foto, Set<CarroAcessorio> carroAcessorios,
			Set<CarroAcessorio> carroAcessorios_1, Set<Aluguel> aluguels, Set<Aluguel> aluguels_1) {
		this.modelocarro = modelocarro;
		this.chassi = chassi;
		this.cor = cor;
		this.placa = placa;
		this.valorDiaria = valorDiaria;
		this.dataCriacao = dataCriacao;
		this.dataModificacao = dataModificacao;
		this.foto = foto;
		this.carroAcessorios = carroAcessorios;
		this.carroAcessorios_1 = carroAcessorios_1;
		this.aluguels = aluguels;
		this.aluguels_1 = aluguels_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codigo", unique = true, nullable = false)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_modelo")
	public Modelocarro getModelocarro() {
		return this.modelocarro;
	}

	public void setModelocarro(Modelocarro modelocarro) {
		this.modelocarro = modelocarro;
	}

	@Column(name = "chassi")
	public String getChassi() {
		return this.chassi;
	}

	public void setChassi(String chassi) {
		this.chassi = chassi;
	}

	@Column(name = "cor")
	public String getCor() {
		return this.cor;
	}

	public void setCor(String cor) {
		this.cor = cor;
	}

	@Column(name = "placa")
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "valor_diaria")
	public BigDecimal getValorDiaria() {
		return this.valorDiaria;
	}

	public void setValorDiaria(BigDecimal valorDiaria) {
		this.valorDiaria = valorDiaria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", length = 26)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_modificacao", length = 26)
	public Date getDataModificacao() {
		return this.dataModificacao;
	}

	public void setDataModificacao(Date dataModificacao) {
		this.dataModificacao = dataModificacao;
	}

	@Column(name = "foto")
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carro")
	public Set<CarroAcessorio> getCarroAcessorios() {
		return this.carroAcessorios;
	}

	public void setCarroAcessorios(Set<CarroAcessorio> carroAcessorios) {
		this.carroAcessorios = carroAcessorios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carro")
	public Set<CarroAcessorio> getCarroAcessorios_1() {
		return this.carroAcessorios_1;
	}

	public void setCarroAcessorios_1(Set<CarroAcessorio> carroAcessorios_1) {
		this.carroAcessorios_1 = carroAcessorios_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carro")
	public Set<Aluguel> getAluguels() {
		return this.aluguels;
	}

	public void setAluguels(Set<Aluguel> aluguels) {
		this.aluguels = aluguels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carro")
	public Set<Aluguel> getAluguels_1() {
		return this.aluguels_1;
	}

	public void setAluguels_1(Set<Aluguel> aluguels_1) {
		this.aluguels_1 = aluguels_1;
	}

}
