package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarroAcessorioId generated by hbm2java
 */
@Embeddable
public class CarroAcessorioId implements java.io.Serializable {

	private long codigoCarro;
	private long codigoAcessorio;

	public CarroAcessorioId() {
	}

	public CarroAcessorioId(long codigoCarro, long codigoAcessorio) {
		this.codigoCarro = codigoCarro;
		this.codigoAcessorio = codigoAcessorio;
	}

	@Column(name = "codigo_carro", nullable = false)
	public long getCodigoCarro() {
		return this.codigoCarro;
	}

	public void setCodigoCarro(long codigoCarro) {
		this.codigoCarro = codigoCarro;
	}

	@Column(name = "codigo_acessorio", nullable = false)
	public long getCodigoAcessorio() {
		return this.codigoAcessorio;
	}

	public void setCodigoAcessorio(long codigoAcessorio) {
		this.codigoAcessorio = codigoAcessorio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarroAcessorioId))
			return false;
		CarroAcessorioId castOther = (CarroAcessorioId) other;

		return (this.getCodigoCarro() == castOther.getCodigoCarro())
				&& (this.getCodigoAcessorio() == castOther.getCodigoAcessorio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCodigoCarro();
		result = 37 * result + (int) this.getCodigoAcessorio();
		return result;
	}

}
