package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CarroAcessorio generated by hbm2java
 */
@Entity
@Table(name = "carro_acessorio", catalog = "locadora")
public class CarroAcessorio implements java.io.Serializable {

	private CarroAcessorioId id;
	private Carro carro;
	private Acessorio acessorio;

	public CarroAcessorio() {
	}

	public CarroAcessorio(CarroAcessorioId id, Carro carro, Acessorio acessorio) {
		this.id = id;
		this.carro = carro;
		this.acessorio = acessorio;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codigoCarro", column = @Column(name = "codigo_carro", nullable = false)),
			@AttributeOverride(name = "codigoAcessorio", column = @Column(name = "codigo_acessorio", nullable = false)) })
	public CarroAcessorioId getId() {
		return this.id;
	}

	public void setId(CarroAcessorioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_carro", nullable = false, insertable = false, updatable = false)
	public Carro getCarro() {
		return this.carro;
	}

	public void setCarro(Carro carro) {
		this.carro = carro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_acessorio", nullable = false, insertable = false, updatable = false)
	public Acessorio getAcessorio() {
		return this.acessorio;
	}

	public void setAcessorio(Acessorio acessorio) {
		this.acessorio = acessorio;
	}

}
