package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fabricante generated by hbm2java
 */
@Entity
@Table(name = "fabricante", catalog = "locadora")
public class Fabricante implements java.io.Serializable {

	private long codigo;
	private String nome;
	private Set<Modelocarro> modelocarros = new HashSet<Modelocarro>(0);
	private Set<Modelocarro> modelocarros_1 = new HashSet<Modelocarro>(0);

	public Fabricante() {
	}

	public Fabricante(long codigo) {
		this.codigo = codigo;
	}

	public Fabricante(long codigo, String nome, Set<Modelocarro> modelocarros, Set<Modelocarro> modelocarros_1) {
		this.codigo = codigo;
		this.nome = nome;
		this.modelocarros = modelocarros;
		this.modelocarros_1 = modelocarros_1;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false)
	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fabricante")
	public Set<Modelocarro> getModelocarros() {
		return this.modelocarros;
	}

	public void setModelocarros(Set<Modelocarro> modelocarros) {
		this.modelocarros = modelocarros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fabricante")
	public Set<Modelocarro> getModelocarros_1() {
		return this.modelocarros_1;
	}

	public void setModelocarros_1(Set<Modelocarro> modelocarros_1) {
		this.modelocarros_1 = modelocarros_1;
	}

}
