package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GeradorCodigo generated by hbm2java
 */
@Entity
@Table(name = "gerador_codigo", catalog = "locadora")
public class GeradorCodigo implements java.io.Serializable {

	private GeradorCodigoId id;

	public GeradorCodigo() {
	}

	public GeradorCodigo(GeradorCodigoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "entidade", column = @Column(name = "ENTIDADE")),
			@AttributeOverride(name = "alocacao", column = @Column(name = "ALOCACAO")) })
	public GeradorCodigoId getId() {
		return this.id;
	}

	public void setId(GeradorCodigoId id) {
		this.id = id;
	}

}
