package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GeradorCodigoId generated by hbm2java
 */
@Embeddable
public class GeradorCodigoId implements java.io.Serializable {

	private String entidade;
	private Integer alocacao;

	public GeradorCodigoId() {
	}

	public GeradorCodigoId(String entidade, Integer alocacao) {
		this.entidade = entidade;
		this.alocacao = alocacao;
	}

	@Column(name = "ENTIDADE")
	public String getEntidade() {
		return this.entidade;
	}

	public void setEntidade(String entidade) {
		this.entidade = entidade;
	}

	@Column(name = "ALOCACAO")
	public Integer getAlocacao() {
		return this.alocacao;
	}

	public void setAlocacao(Integer alocacao) {
		this.alocacao = alocacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GeradorCodigoId))
			return false;
		GeradorCodigoId castOther = (GeradorCodigoId) other;

		return ((this.getEntidade() == castOther.getEntidade()) || (this.getEntidade() != null
				&& castOther.getEntidade() != null && this.getEntidade().equals(castOther.getEntidade())))
				&& ((this.getAlocacao() == castOther.getAlocacao()) || (this.getAlocacao() != null
						&& castOther.getAlocacao() != null && this.getAlocacao().equals(castOther.getAlocacao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEntidade() == null ? 0 : this.getEntidade().hashCode());
		result = 37 * result + (getAlocacao() == null ? 0 : this.getAlocacao().hashCode());
		return result;
	}

}
