package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modelocarro generated by hbm2java
 */
@Entity
@Table(name = "modelocarro", catalog = "locadora")
public class Modelocarro implements java.io.Serializable {

	private Long codigo;
	private Fabricante fabricante;
	private String categoria;
	private String descricao;
	private Set<Carro> carros = new HashSet<Carro>(0);
	private Set<Carro> carros_1 = new HashSet<Carro>(0);

	public Modelocarro() {
	}

	public Modelocarro(Fabricante fabricante, String categoria, String descricao, Set<Carro> carros,
			Set<Carro> carros_1) {
		this.fabricante = fabricante;
		this.categoria = categoria;
		this.descricao = descricao;
		this.carros = carros;
		this.carros_1 = carros_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codigo", unique = true, nullable = false)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_fabricante")
	public Fabricante getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(Fabricante fabricante) {
		this.fabricante = fabricante;
	}

	@Column(name = "categoria")
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelocarro")
	public Set<Carro> getCarros() {
		return this.carros;
	}

	public void setCarros(Set<Carro> carros) {
		this.carros = carros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelocarro")
	public Set<Carro> getCarros_1() {
		return this.carros_1;
	}

	public void setCarros_1(Set<Carro> carros_1) {
		this.carros_1 = carros_1;
	}

}
