package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Motorista generated by hbm2java
 */
@Entity
@Table(name = "motorista", catalog = "locadora")
public class Motorista implements java.io.Serializable {

	private long codigo;
	private Pessoa pessoa;
	private String numeroCnh;
	private Set<Aluguel> aluguels = new HashSet<Aluguel>(0);
	private Set<Aluguel> aluguels_1 = new HashSet<Aluguel>(0);

	public Motorista() {
	}

	public Motorista(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Motorista(Pessoa pessoa, String numeroCnh, Set<Aluguel> aluguels, Set<Aluguel> aluguels_1) {
		this.pessoa = pessoa;
		this.numeroCnh = numeroCnh;
		this.aluguels = aluguels;
		this.aluguels_1 = aluguels_1;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pessoa"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "codigo", unique = true, nullable = false)
	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "numero_cnh")
	public String getNumeroCnh() {
		return this.numeroCnh;
	}

	public void setNumeroCnh(String numeroCnh) {
		this.numeroCnh = numeroCnh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motorista")
	public Set<Aluguel> getAluguels() {
		return this.aluguels;
	}

	public void setAluguels(Set<Aluguel> aluguels) {
		this.aluguels = aluguels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motorista")
	public Set<Aluguel> getAluguels_1() {
		return this.aluguels_1;
	}

	public void setAluguels_1(Set<Aluguel> aluguels_1) {
		this.aluguels_1 = aluguels_1;
	}

}
