package com.algaworks.locadora.model;
// Generated 17/03/2019 17:32:54 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", catalog = "locadora")
public class Pessoa implements java.io.Serializable {

	private Long codigo;
	private String cpf;
	private Date dataNascimento;
	private String nome;
	private String sexo;
	private int tipoPessoa;
	private Motorista motorista;
	private Motorista motorista;
	private Funcionario funcionario;
	private Funcionario funcionario;

	public Pessoa() {
	}

	public Pessoa(int tipoPessoa) {
		this.tipoPessoa = tipoPessoa;
	}

	public Pessoa(String cpf, Date dataNascimento, String nome, String sexo, int tipoPessoa, Motorista motorista,
			Motorista motorista, Funcionario funcionario, Funcionario funcionario) {
		this.cpf = cpf;
		this.dataNascimento = dataNascimento;
		this.nome = nome;
		this.sexo = sexo;
		this.tipoPessoa = tipoPessoa;
		this.motorista = motorista;
		this.motorista = motorista;
		this.funcionario = funcionario;
		this.funcionario = funcionario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codigo", unique = true, nullable = false)
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	@Column(name = "cpf")
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", length = 10)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "sexo")
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "tipo_pessoa", nullable = false)
	public int getTipoPessoa() {
		return this.tipoPessoa;
	}

	public void setTipoPessoa(int tipoPessoa) {
		this.tipoPessoa = tipoPessoa;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Motorista getMotorista() {
		return this.motorista;
	}

	public void setMotorista(Motorista motorista) {
		this.motorista = motorista;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Motorista getMotorista() {
		return this.motorista;
	}

	public void setMotorista(Motorista motorista) {
		this.motorista = motorista;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

}
